#!/usr/bin/env python3
"""Generate anti-detect JS patches from browserSignature in storageState.json.
Used by both Playwright (anti-detect.js) and Chrome DevTools (content.js) containers.
Also prints bash variable assignments for UA/lang/viewport to stdout."""
import json, sys, os

storage_path = sys.argv[1] if len(sys.argv) > 1 else "/app/storageState.json"
output_js = sys.argv[2] if len(sys.argv) > 2 else "/app/anti-detect.js"
mode = sys.argv[3] if len(sys.argv) > 3 else "env"  # "env" = print bash vars, "quiet" = don't

# Load signature
sig = {}
try:
    with open(storage_path) as f:
        data = json.load(f)
        sig = data.get("browserSignature") or {}
except Exception as e:
    print(f'echo "WARNING: Could not read signature: {e}"', file=sys.stderr)

# Extract values with defaults
platform = sig.get("platform", "Win32")
device_memory = sig.get("deviceMemory", 8)
hardware_concurrency = sig.get("hardwareConcurrency", 16)
max_touch_points = sig.get("maxTouchPoints", 0)
languages = json.dumps(sig.get("languages", ["en-US", "en"]))
connection_rtt = sig.get("connectionRtt", 50)
connection_type = sig.get("connectionType", "4g")
connection_downlink = sig.get("connectionDownlink", 10)
color_depth = sig.get("screenColorDepth", 24)
pixel_ratio = sig.get("devicePixelRatio", 1)
do_not_track = sig.get("doNotTrack")
ua = sig.get("userAgent", "")
lang_list = sig.get("languages", ["en-US", "en"])
screen_w = sig.get("screenWidth", 1920)
screen_h = sig.get("screenHeight", 1080)

# Generate JS
js = f"""// AUTO-GENERATED by generate-anti-detect.py — do not edit manually
// Anti-detection patches with browser signature from storageState.json

Object.defineProperty(navigator, 'webdriver', {{ get: () => false }});
Object.defineProperty(navigator, 'platform', {{ get: () => '{platform}' }});
Object.defineProperty(navigator, 'deviceMemory', {{ get: () => {device_memory} }});
Object.defineProperty(navigator, 'hardwareConcurrency', {{ get: () => {hardware_concurrency} }});
Object.defineProperty(navigator, 'maxTouchPoints', {{ get: () => {max_touch_points} }});
Object.defineProperty(navigator, 'languages', {{ get: () => Object.freeze({languages}) }});

if (navigator.connection) {{
  Object.defineProperty(navigator.connection, 'rtt', {{ get: () => {connection_rtt} }});
  Object.defineProperty(navigator.connection, 'effectiveType', {{ get: () => '{connection_type}' }});
  Object.defineProperty(navigator.connection, 'downlink', {{ get: () => {connection_downlink} }});
}}

Object.defineProperty(screen, 'colorDepth', {{ get: () => {color_depth} }});
Object.defineProperty(screen, 'pixelDepth', {{ get: () => {color_depth} }});
Object.defineProperty(window, 'devicePixelRatio', {{ get: () => {pixel_ratio} }});

if (!window.chrome) window.chrome = {{}};
if (!window.chrome.runtime) {{
  window.chrome.runtime = {{ connect: () => {{}}, sendMessage: () => {{}} }};
}}

if (typeof Notification !== 'undefined') {{
  Object.defineProperty(Notification, 'permission', {{ get: () => 'default' }});
}}
"""

if do_not_track is not None:
    js += f"\nObject.defineProperty(navigator, 'doNotTrack', {{ get: () => '{do_not_track}' }});\n"

with open(output_js, "w") as f:
    f.write(js)

print(f"Generated {output_js}: platform={platform}, languages={languages}, pixelRatio={pixel_ratio}", file=sys.stderr)

# Print bash variable assignments to stdout (for entrypoint eval)
if mode == "env":
    print(f'SIG_UA="{ua}"')
    print(f'SIG_LANG="{",".join(lang_list)}"')
    print(f'SIG_VIEWPORT="{screen_w}x{screen_h}"')
