#!/usr/bin/env python3
"""Generate content.js with browser signature patches + IndexedDB injection from storageState.json."""
import json, sys, os

storage_path = sys.argv[1] if len(sys.argv) > 1 else "/app/storageState.json"
output_path = sys.argv[2] if len(sys.argv) > 2 else "/app/extensions/cookie-injector/content.js"

# Load full storageState
data = {}
sig = {}
try:
    with open(storage_path) as f:
        data = json.load(f)
        sig = data.get("browserSignature", {})
except Exception as e:
    print(f"WARNING: Could not read storageState: {e}", file=sys.stderr)

# Extract values with defaults
platform = sig.get("platform", "Win32")
device_memory = sig.get("deviceMemory", 8)
hardware_concurrency = sig.get("hardwareConcurrency", 16)
max_touch_points = sig.get("maxTouchPoints", 0)
languages = json.dumps(sig.get("languages", ["en-US", "en"]))
connection_rtt = sig.get("connectionRtt", 50)
connection_type = sig.get("connectionType", "4g")
connection_downlink = sig.get("connectionDownlink", 10)
color_depth = sig.get("screenColorDepth", 24)
pixel_ratio = sig.get("devicePixelRatio", 1)
do_not_track = sig.get("doNotTrack")

js = f"""// AUTO-GENERATED by generate-content.py — do not edit manually
// Anti-detection patches with browser signature from storageState.json

// navigator.webdriver — the #1 bot detection signal
Object.defineProperty(navigator, 'webdriver', {{ get: () => false }});

// navigator.platform
Object.defineProperty(navigator, 'platform', {{ get: () => '{platform}' }});

// navigator.deviceMemory
Object.defineProperty(navigator, 'deviceMemory', {{ get: () => {device_memory} }});

// navigator.hardwareConcurrency
Object.defineProperty(navigator, 'hardwareConcurrency', {{ get: () => {hardware_concurrency} }});

// navigator.maxTouchPoints
Object.defineProperty(navigator, 'maxTouchPoints', {{ get: () => {max_touch_points} }});

// navigator.languages
Object.defineProperty(navigator, 'languages', {{ get: () => Object.freeze({languages}) }});

// navigator.connection
if (navigator.connection) {{
  Object.defineProperty(navigator.connection, 'rtt', {{ get: () => {connection_rtt} }});
  Object.defineProperty(navigator.connection, 'effectiveType', {{ get: () => '{connection_type}' }});
  Object.defineProperty(navigator.connection, 'downlink', {{ get: () => {connection_downlink} }});
}}

// screen properties
Object.defineProperty(screen, 'colorDepth', {{ get: () => {color_depth} }});
Object.defineProperty(screen, 'pixelDepth', {{ get: () => {color_depth} }});
Object.defineProperty(window, 'devicePixelRatio', {{ get: () => {pixel_ratio} }});

// chrome.runtime — present in real Chrome
if (!window.chrome) window.chrome = {{}};
if (!window.chrome.runtime) {{
  window.chrome.runtime = {{ connect: () => {{}}, sendMessage: () => {{}} }};
}}

// Notification.permission
if (typeof Notification !== 'undefined') {{
  Object.defineProperty(Notification, 'permission', {{ get: () => 'default' }});
}}
"""

# Add doNotTrack if present
if do_not_track is not None:
    js += f"""
// navigator.doNotTrack
Object.defineProperty(navigator, 'doNotTrack', {{ get: () => '{do_not_track}' }});
"""

# ---------------------------------------------------------------------------
# IndexedDB injection — origin-aware, same approach as generate-anti-detect.py
# ---------------------------------------------------------------------------
idb_data = data.get("indexedDB")
if idb_data and isinstance(idb_data, dict) and any(idb_data.values()):
    idb_json = json.dumps(idb_data)
    js += f"""
// ---------------------------------------------------------------------------
// IndexedDB injection — origin-aware, pre-populate from storageState.json
// ---------------------------------------------------------------------------
(function() {{
  const __idbByOrigin = {idb_json};
  const __idbInjected = new Set();
  const __origOpen = indexedDB.open.bind(indexedDB);

  function __getOriginDBs() {{
    const origin = location.origin || location.protocol + '//' + location.host;
    const dbs = __idbByOrigin[origin];
    if (!dbs) return {{}};
    const map = {{}};
    for (const db of dbs) map[db.name] = db;
    return map;
  }}

  indexedDB.open = function(name, version) {{
    const originDBs = __getOriginDBs();
    const dbData = originDBs[name];
    const injectedKey = location.origin + '::' + name;

    if (!dbData || __idbInjected.has(injectedKey)) {{
      return __origOpen(name, version);
    }}

    const targetVersion = dbData.version || version;
    const request = __origOpen(name, targetVersion);

    let _userOnSuccess = null;
    const _injectRecords = function(event) {{
      const db = event.target.result;
      __idbInjected.add(injectedKey);
      const storesToInject = dbData.objectStores.filter(s => db.objectStoreNames.contains(s.name));
      if (storesToInject.length === 0) {{
        if (_userOnSuccess) _userOnSuccess.call(this, event);
        return;
      }}
      try {{
        const tx = db.transaction(storesToInject.map(s => s.name), 'readwrite');
        for (const storeData of storesToInject) {{
          const store = tx.objectStore(storeData.name);
          for (const record of (storeData.records || [])) {{
            try {{
              if (record.key !== undefined && record.key !== null && !storeData.keyPath) {{
                store.put(record.value, record.key);
              }} else {{
                store.put(record.value);
              }}
            }} catch(e) {{}}
          }}
        }}
        tx.oncomplete = function() {{
          if (_userOnSuccess) _userOnSuccess.call(request, event);
        }};
        tx.onerror = function() {{
          if (_userOnSuccess) _userOnSuccess.call(request, event);
        }};
      }} catch(e) {{
        if (_userOnSuccess) _userOnSuccess.call(this, event);
      }}
    }};

    Object.defineProperty(request, 'onsuccess', {{
      get() {{ return _injectRecords; }},
      set(fn) {{ _userOnSuccess = fn; }},
      configurable: true,
    }});

    const _origAddEventListener = request.addEventListener.bind(request);
    request.addEventListener = function(type, listener, options) {{
      if (type === 'success' && dbData && !__idbInjected.has(injectedKey)) {{
        _userOnSuccess = listener;
        return _origAddEventListener(type, _injectRecords, options);
      }}
      return _origAddEventListener(type, listener, options);
    }};

    return request;
  }};
}})();
"""
    idb_origin_count = len(idb_data)
    idb_db_count = sum(len(dbs) for dbs in idb_data.values())
    idb_record_count = sum(
        len(r) for dbs in idb_data.values() for db in dbs for s in db.get("objectStores", []) for r in [s.get("records", [])]
    )
    print(f"IndexedDB injection: {idb_origin_count} origins, {idb_db_count} databases, {idb_record_count} records")

with open(output_path, "w") as f:
    f.write(js)

print(f"Generated {output_path} with signature: platform={platform}, languages={languages}, pixelRatio={pixel_ratio}")
